SELECT A.BOOK_ID, B.AUTHOR_NAME, DATE_FORMAT(A.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM
(SELECT *
 FROM BOOK
 WHERE CATEGORY = '경제') AS A
JOIN AUTHOR AS B
ON A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY PUBLISHED_DATE